# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    exclude: ^prototypes/
- repo: https://github.com/regebro/pyroma
  rev: "5.0"
  hooks:
  - id: pyroma
- repo: https://github.com/miki725/pre-commit-twine-check
  rev: '0.1'
  hooks:
  - id: twine-check
